"use client";

/**
 * InlineContractForm
 *
 * Rendered on the accept-sent page immediately after Martina accepts.
 * Uses the short-lived admin_token generated by /api/accept — no bookmark needed.
 * Service description is pre-filled from a programme template.
 * Martina reviews, optionally edits one field, and sends in one click.
 */

import { useState, useEffect } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";

// Mirrors SERVICE_DESCRIPTION_TEMPLATES from lib/email-templates.ts (client-safe copy)
const TEMPLATES: Record<string, string> = {
  "sober-muse":
    "90-day private coaching programme — The Sober Muse Method. Includes weekly 60-minute sessions via Zoom, asynchronous support between sessions, and direct access to Martina throughout. Focused on the specific work agreed in our private consultation.",
  empowerment:
    "Bespoke Female Empowerment & Leadership coaching programme over 3–12 months. Includes bi-weekly 60-minute sessions via Zoom, written reflection work between sessions, and sustained direct support throughout. Scope and duration as agreed in our private consultation.",
  consultation:
    "Single private consultation — 45 minutes via Zoom. A focused, confidential conversation on the specific questions and direction agreed between us. Fee credited in full to the programme investment upon enrolment.",
};

const FEES: Record<string, string> = {
  "sober-muse": "€5,000",
  empowerment: "€7,500",
  consultation: "€450",
};

const LABELS: Record<string, string> = {
  "sober-muse": "The Sober Muse Method",
  empowerment: "Female Empowerment & Leadership",
  consultation: "Private Consultation",
};

function todayFormatted(): string {
  return new Date().toLocaleDateString("de-DE", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });
}

const FormSchema = z.object({
  serviceDescription: z.string().min(10, "Service description required"),
  fee: z.string().min(1, "Fee required"),
  deliveryMethod: z.enum(["Online", "In-person", "Telephone"]),
  location: z.string().optional(),
  contractDate: z.string().min(1, "Date required"),
});

type FormData = z.infer<typeof FormSchema>;

interface Props {
  adminToken: string;
  email: string;
  firstName: string;
  programme: string;
}

export function InlineContractForm({ adminToken, email, firstName, programme }: Props) {
  const [status, setStatus] = useState<"idle" | "sending" | "sent" | "error">("idle");
  const [errorMsg, setErrorMsg] = useState("");

  const {
    register,
    handleSubmit,
    watch,
    setValue,
    formState: { errors },
  } = useForm<FormData>({
    resolver: zodResolver(FormSchema),
    defaultValues: {
      serviceDescription: TEMPLATES[programme] ?? "",
      fee: FEES[programme] ?? "",
      deliveryMethod: "Online",
      contractDate: todayFormatted(),
    },
  });

  // Re-sync defaults if programme changes (shouldn't happen here, but defensive)
  useEffect(() => {
    setValue("serviceDescription", TEMPLATES[programme] ?? "");
    setValue("fee", FEES[programme] ?? "");
  }, [programme, setValue]);

  const deliveryMethod = watch("deliveryMethod");

  const onSubmit = async (data: FormData) => {
    setStatus("sending");
    setErrorMsg("");
    try {
      const res = await fetch("/api/contract/send", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          adminToken,
          email,
          firstName,
          programme,
          serviceDescription: data.serviceDescription,
          fee: data.fee,
          deliveryMethod: data.deliveryMethod,
          location: data.location,
          contractDate: data.contractDate,
        }),
      });
      const json = await res.json();
      if (!res.ok) {
        setErrorMsg(json.error ?? "Something went wrong.");
        setStatus("error");
        return;
      }
      setStatus("sent");
    } catch {
      setErrorMsg("Network error — check your connection.");
      setStatus("error");
    }
  };

  if (status === "sent") {
    return (
      <div className="mt-10 pt-8 border-t border-cream/10 text-center">
        <div className="w-10 h-10 rounded-full border border-pink/40 flex items-center justify-center mx-auto mb-5">
          <svg width="16" height="16" viewBox="0 0 16 16" fill="none" aria-hidden>
            <path d="M3 8.5l3.5 3.5 6-7" stroke="#F942AA" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
          </svg>
        </div>
        <p className="font-[family-name:var(--font-body)] text-[11px] uppercase tracking-[0.2em] text-pink/60 mb-2">
          Contract sent
        </p>
        <p className="font-[family-name:var(--font-display)] italic text-[22px] text-cream leading-tight">
          {firstName} has the contract.
        </p>
        <p className="mt-3 text-[13px] text-cream/50 font-[family-name:var(--font-body)] leading-relaxed">
          Once she signs, her intake form fires automatically.
          <br />
          You&rsquo;ll receive a copy of the signed contract.
        </p>
      </div>
    );
  }

  const inputClass =
    "w-full bg-cream/5 border border-cream/15 text-cream placeholder-cream/25 px-4 py-3 text-[14px] font-[family-name:var(--font-body)] focus:outline-none focus:border-pink/40 transition-colors";
  const labelClass =
    "block text-[10px] uppercase tracking-[0.2em] text-cream/35 font-[family-name:var(--font-body)] mb-2";
  const errClass = "mt-1 text-[12px] text-pink/80 font-[family-name:var(--font-body)]";

  return (
    <div className="mt-10 pt-8 border-t border-cream/10">

      <p className="font-[family-name:var(--font-body)] text-[10px] uppercase tracking-[0.22em] text-cream/30 mb-2">
        Next step
      </p>
      <p className="font-[family-name:var(--font-display)] italic text-[20px] text-cream/80 mb-1 leading-tight">
        Send the coaching contract.
      </p>
      <p className="text-[13px] text-cream/45 font-[family-name:var(--font-body)] mb-7 leading-relaxed">
        After the consultation. The service description is pre-filled — edit as needed.
      </p>

      <form onSubmit={handleSubmit(onSubmit)} noValidate className="text-left space-y-5">

        {/* Programme label — read-only display */}
        <div className="bg-cream/5 border border-cream/10 px-4 py-3">
          <p className="text-[10px] uppercase tracking-widest text-cream/30 mb-1 font-[family-name:var(--font-body)]">
            Programme
          </p>
          <p className="text-[14px] text-cream/70 font-[family-name:var(--font-body)]">
            {LABELS[programme] ?? programme}
          </p>
        </div>

        {/* Service description — the ONE field Martina edits */}
        <div>
          <label className={labelClass}>
            Service description
            <span className="ml-2 text-pink/50 normal-case tracking-normal">
              — review and edit
            </span>
          </label>
          <textarea
            rows={4}
            className={`${inputClass} resize-y`}
            {...register("serviceDescription")}
          />
          {errors.serviceDescription && (
            <p className={errClass}>{errors.serviceDescription.message}</p>
          )}
        </div>

        {/* Fee */}
        <div>
          <label className={labelClass}>Investment</label>
          <input type="text" className={inputClass} {...register("fee")} />
          {errors.fee && <p className={errClass}>{errors.fee.message}</p>}
        </div>

        {/* Delivery method */}
        <div>
          <label className={labelClass}>Format</label>
          <div className="flex gap-6">
            {(["Online", "In-person", "Telephone"] as const).map((m) => (
              <label key={m} className="flex items-center gap-2 cursor-pointer">
                <input type="radio" value={m} {...register("deliveryMethod")} className="accent-pink cursor-pointer" />
                <span className="text-[13px] text-cream/65 font-[family-name:var(--font-body)]">{m}</span>
              </label>
            ))}
          </div>
        </div>

        {/* Location — only for in-person */}
        {deliveryMethod === "In-person" && (
          <div>
            <label className={labelClass}>Location</label>
            <input
              type="text"
              placeholder="Steinkreuzstr. 26b, 76228 Karlsruhe"
              className={inputClass}
              {...register("location")}
            />
          </div>
        )}

        {/* Contract date */}
        <div>
          <label className={labelClass}>Contract date</label>
          <input type="text" className={inputClass} {...register("contractDate")} />
          {errors.contractDate && <p className={errClass}>{errors.contractDate.message}</p>}
        </div>

        {/* Error */}
        {status === "error" && (
          <div className="bg-pink/10 border border-pink/20 px-4 py-3">
            <p className="text-[13px] text-pink/90 font-[family-name:var(--font-body)]">{errorMsg}</p>
          </div>
        )}

        {/* Submit */}
        <button
          type="submit"
          disabled={status === "sending"}
          className="w-full bg-plum hover:bg-plum-deep text-cream text-[11px] uppercase tracking-[0.22em] py-4 transition-colors disabled:opacity-50 font-[family-name:var(--font-body)] cursor-pointer"
        >
          {status === "sending" ? "Sending…" : `Send contract to ${firstName}`}
        </button>

        <p className="text-[11px] text-cream/25 font-[family-name:var(--font-body)] text-center leading-relaxed">
          Client receives the signing link by email. Once signed, her intake form fires automatically.
        </p>

      </form>
    </div>
  );
}
