import type { Metadata } from "next";
import { buildMetadata } from "@/lib/metadata";
import { InlineContractForm } from "@/components/contract/InlineContractForm";

export const metadata: Metadata = buildMetadata({
  title: "Application accepted",
  noIndex: true,
});

export default async function AcceptSentPage({
  searchParams,
}: {
  searchParams: Promise<{
    name?: string;
    email?: string;
    programme?: string;
    admin_token?: string;
  }>;
}) {
  const params = await searchParams;
  const name        = params.name        ?? "the applicant";
  const email       = params.email       ?? "";
  const programme   = params.programme   ?? "";
  const adminToken  = params.admin_token ?? "";

  // Inline contract form is available only when admin_token is present
  // (generated by /api/accept — scoped to this specific accept action).
  // Falls back to the old admin link if token is missing (e.g., old accept emails).
  const hasToken = adminToken.length > 0;

  return (
    <section className="min-h-screen bg-aubergine px-6 py-16">
      <div className="max-w-md mx-auto">

        {/* ── STEP 1: Booking link sent ───────────────────────── */}
        <div className="text-center">

          {/* Pink hairline */}
          <div
            aria-hidden
            className="h-px w-16 mx-auto mb-10"
            style={{ background: "linear-gradient(to right, transparent, #F942AA, transparent)" }}
          />

          {/* Check mark */}
          <div className="w-12 h-12 rounded-full border border-pink/40 flex items-center justify-center mx-auto mb-8">
            <svg width="20" height="20" viewBox="0 0 20 20" fill="none" aria-hidden>
              <path
                d="M4 10.5l4.5 4.5 7.5-9"
                stroke="#F942AA"
                strokeWidth="1.5"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
            </svg>
          </div>

          <p className="font-[family-name:var(--font-body)] text-[11px] uppercase tracking-[0.26em] text-cream/40 mb-4">
            Step 1 of 2 — done
          </p>

          <h1 className="font-[family-name:var(--font-display)] italic text-[32px] md:text-[40px] leading-[1.1] text-cream mb-6">
            {name} has her booking link.
          </h1>

          <p className="text-[15px] leading-[1.75] text-cream/60 font-[family-name:var(--font-body)] mb-2">
            The acceptance email — with{" "}
            <span className="text-cream/80">/book?token=approved</span> — has been sent to{" "}
            {email ? (
              <span className="text-cream/80">{email}</span>
            ) : (
              "her inbox"
            )}.
          </p>

          <p className="text-[12px] leading-[1.7] text-cream/35 font-[family-name:var(--font-body)] mt-4">
            Brevo: <span className="text-cream/55">accepted</span>
          </p>
        </div>

        {/* ── WHAT HAPPENS NEXT (automated chain) ─────────────── */}
        <div className="mt-10 pt-8 border-t border-cream/10">
          <p className="font-[family-name:var(--font-body)] text-[10px] uppercase tracking-[0.22em] text-cream/25 mb-5 text-center">
            The automated chain after you send the contract
          </p>
          <ol className="space-y-3">
            {[
              ["She books the consultation", "via the booking link above"],
              ["You send the contract below", "takes 30 seconds — one field to edit"],
              ["She signs digitally", "her intake form fires automatically"],
              ["You receive her intake", "she&rsquo;s ready to begin"],
            ].map(([step, sub], i) => (
              <li key={i} className="flex gap-4">
                <span className="font-[family-name:var(--font-body)] text-[11px] text-pink/50 mt-0.5 flex-shrink-0 w-5 text-center">
                  {String(i + 1).padStart(2, "0")}
                </span>
                <div>
                  <p
                    className="text-[13px] text-cream/70 font-[family-name:var(--font-body)]"
                    dangerouslySetInnerHTML={{ __html: step }}
                  />
                  <p
                    className="text-[11px] text-cream/35 font-[family-name:var(--font-body)]"
                    dangerouslySetInnerHTML={{ __html: sub }}
                  />
                </div>
              </li>
            ))}
          </ol>
        </div>

        {/* ── STEP 2: Inline contract form OR fallback link ─────── */}
        {hasToken && email && programme ? (
          <InlineContractForm
            adminToken={adminToken}
            email={email}
            firstName={name}
            programme={programme}
          />
        ) : (
          /* Fallback: no token (old accept email or direct navigation) */
          <div className="mt-10 pt-8 border-t border-cream/10 text-center">
            <p className="font-[family-name:var(--font-body)] text-[11px] uppercase tracking-[0.2em] text-cream/30 mb-3">
              Step 2 — send the contract
            </p>
            <p className="text-[13px] text-cream/50 font-[family-name:var(--font-body)] leading-relaxed mb-4">
              Use your bookmarked admin link to send the coaching contract.
            </p>
            <a
              href={`/admin/contract${
                email || programme
                  ? `?${new URLSearchParams({
                      ...(email && { email }),
                      ...(name !== "the applicant" && { firstName: name }),
                      ...(programme && { programme }),
                    }).toString()}`
                  : ""
              }`}
              className="inline-block text-[11px] uppercase tracking-[0.2em] text-pink/70 hover:text-pink transition-colors font-[family-name:var(--font-body)]"
            >
              Open contract form &rarr;
            </a>
            <p className="mt-2 text-[11px] text-cream/25 font-[family-name:var(--font-body)]">
              Add <span className="text-cream/40">?secret=…</span> from your bookmarked URL.
            </p>
          </div>
        )}

        <div className="mt-12 pt-6 border-t border-cream/10 text-center">
          <p className="font-[family-name:var(--font-display)] italic text-[20px] text-cream/60">
            Martina
          </p>
        </div>

      </div>
    </section>
  );
}
